version: '3'
services:
  ipfs-host1:
    container_name: ipfs-host1
    image: ipfs/kubo:latest
    volumes:
      - ./clean-bootstrap.sh:/container-init.d/clean-bootstrap.sh
      - ./ipfs-host1/data:/data/ipfs
      - ./ipfs-host1/export:/export
    networks:
      - net1

  ipfs-host2:
    container_name: ipfs-host2
    image: ipfs/kubo:latest
    volumes:
      - ./clean-bootstrap.sh:/container-init.d/clean-bootstrap.sh
      - ./ipfs-host2/data:/data/ipfs
      - ./ipfs-host2/export:/export
    networks:
      - net2

  ipfs-host3:
    container_name: ipfs-host3
    image: ipfs/kubo:latest
    volumes:
      - ./clean-bootstrap.sh:/container-init.d/clean-bootstrap.sh
      - ./ipfs-host3/data:/data/ipfs
      - ./ipfs-host3/export:/export
    networks:
      - net3

networks:
  net1:
    driver: ipvlan
    driver_opts:
      parent: eth0
      ipvlan_mode: l3
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
  net2:
    driver: ipvlan
    driver_opts:
      parent: eth0
      ipvlan_mode: l3
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24
  net3:
    driver: ipvlan
    driver_opts:
      parent: eth0
      ipvlan_mode: l3
    ipam:
      driver: default
      config:
        - subnet: 192.168.3.0/24
