version: '3'
services:
  ipfs-client-webui:
    container_name: ipfs-client-webui
    image: ipfs/kubo:latest
    depends_on:
      - ipfs-bootstrap1
      - ipfs-bootstrap2
      - ipfs-bootstrap3
    volumes:
      - ./10import-webui.sh:/container-init.d/10import-webui.sh
      - ./20clean-bootstrap.sh:/container-init.d/20clean-bootstrap.sh
      - ./ipfs-client-webui/data:/data/ipfs
      - ./ipfs-client-webui/export:/export
      - ./simulation:/simulation
      - ./webui.car:/export/webui.car
      - ./swarm.key:/data/ipfs/swarm.key
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:5001:5001"

  ipfs-bootstrap1:
    container_name: ipfs-bootstrap1
    image: ipfs/kubo:latest
    volumes:
      - ./20clean-bootstrap.sh:/container-init.d/20clean-bootstrap.sh      
      - ./30log-boostrap.sh:/container-init.d/30log-boostrap.sh
      - ./ipfs-bootstrap1/data:/data/ipfs
      - ./ipfs-bootstrap1/export:/export
      - ./simulation:/simulation
      - ./swarm.key:/data/ipfs/swarm.key
    ports:
      - "127.0.0.1:5002:5001"
      - "4002:4001"

  ipfs-bootstrap2:
    container_name: ipfs-bootstrap2
    image: ipfs/kubo:latest
    volumes:
      - ./20clean-bootstrap.sh:/container-init.d/20clean-bootstrap.sh      
      - ./30log-boostrap.sh:/container-init.d/30log-boostrap.sh
      - ./ipfs-bootstrap2/data:/data/ipfs
      - ./ipfs-bootstrap2/export:/export
      - ./simulation:/simulation
      - ./swarm.key:/data/ipfs/swarm.key
    ports:
      - "127.0.0.1:5003:5001"
      - "4003:4001"

  ipfs-bootstrap3:
    container_name: ipfs-bootstrap3
    image: ipfs/kubo:latest
    volumes:
      - ./20clean-bootstrap.sh:/container-init.d/20clean-bootstrap.sh      
      - ./30log-boostrap.sh:/container-init.d/30log-boostrap.sh
      - ./ipfs-bootstrap3/data:/data/ipfs
      - ./ipfs-bootstrap3/export:/export
      - ./simulation:/simulation
      - ./swarm.key:/data/ipfs/swarm.key
    ports:
      - "127.0.0.1:5004:5001"
      - "4004:4001"

  ipfs-client1:
    container_name: ipfs-client1
    image: ipfs/kubo:latest
    depends_on:
      - ipfs-bootstrap1
      - ipfs-bootstrap2
      - ipfs-bootstrap3
    volumes:
      - ./20clean-bootstrap.sh:/container-init.d/20clean-bootstrap.sh
      - ./ipfs-client1/data:/data/ipfs
      - ./ipfs-client1/export:/export
      - ./simulation:/simulation
      - ./swarm.key:/data/ipfs/swarm.key
    ports:
      - "127.0.0.1:5005:5001"

  ipfs-client2:
    container_name: ipfs-client2
    image: ipfs/kubo:latest
    depends_on:
      - ipfs-bootstrap1
      - ipfs-bootstrap2
      - ipfs-bootstrap3
    volumes:
      - ./20clean-bootstrap.sh:/container-init.d/20clean-bootstrap.sh
      - ./ipfs-client2/data:/data/ipfs
      - ./ipfs-client2/export:/export
      - ./simulation:/simulation
      - ./swarm.key:/data/ipfs/swarm.key
    ports:
      - "127.0.0.1:5006:5001"

  ipfs-client3:
    container_name: ipfs-client3
    image: ipfs/kubo:latest
    depends_on:
      - ipfs-bootstrap1
      - ipfs-bootstrap2
      - ipfs-bootstrap3
    volumes:
      - ./20clean-bootstrap.sh:/container-init.d/20clean-bootstrap.sh
      - ./ipfs-client3/data:/data/ipfs
      - ./ipfs-client3/export:/export
      - ./simulation:/simulation
      - ./swarm.key:/data/ipfs/swarm.key
    ports:
      - "127.0.0.1:5007:5001"
