version: '3'
services:
  ipfs-host:
    image: ipfs/kubo:latest
    volumes:
      - ./data:/data/ipfs
      - ./export:/export
    ports:
      - "4001:4001"
      - "4001:4001/udp"
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:5001:5001"