version: '3'
services:
  ipfs-host1:
    container_name: ipfs-host1
    image: ipfs/kubo:latest
    environment:
      - IPFS_SWARM_KEY_FILE=/export/swarm.key
    volumes:
      - ./clean-bootstrap.sh:/container-init.d/clean-bootstrap.sh
      - ./ipfs-host1/data:/data/ipfs
      - ./ipfs-host1/export:/export
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:5001:5001"

  ipfs-host2:
    container_name: ipfs-host2
    image: ipfs/kubo:latest
    environment:
      - IPFS_SWARM_KEY_FILE=/export/swarm.key
    volumes:
      - ./clean-bootstrap.sh:/container-init.d/clean-bootstrap.sh
      - ./ipfs-host2/data:/data/ipfs
      - ./ipfs-host2/export:/export
    ports:
      - "127.0.0.1:5002:5001"

  ipfs-host3:
    container_name: ipfs-host3
    image: ipfs/kubo:latest
    environment:
      - IPFS_SWARM_KEY_FILE=/export/swarm.key
    volumes:
      - ./clean-bootstrap.sh:/container-init.d/clean-bootstrap.sh
      - ./ipfs-host3/data:/data/ipfs
      - ./ipfs-host3/export:/export
    ports:
      - "127.0.0.1:5003:5001"
